name: Go CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - go
  pull_request:
    branches:
      - main
      - go

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"

      - name: Build CLI
        run: go build -v -o teamwerx ./cmd/teamwerx

      - name: Run tests
        run: make test

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54.2
